'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCompte
    Public Property email As String
    Public Property mdp As String
    Public Property premiereConnexion As Boolean
    Public Property noClient As Integer

    Public Overridable Property tblClient As tblClient

End Class
