'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCommunique
    Public Property noCommunique As Short
    Public Property titreCommunique As String
    Public Property contCommunique As String
    Public Property noHotel As Byte
    Public Property etatCommunique As String

    Public Overridable Property tblHotel As tblHotel

End Class
