'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblClient
    Public Property noClient As Integer
    Public Property nomClient As String
    Public Property prenClient As String
    Public Property noTelClient As String
    Public Property noCellClient As String
    Public Property adrClient As String
    Public Property emailClient As String
    Public Property typeCarteCredit As String
    Public Property noCarteCredit As String
    Public Property dateExpiration As String
    Public Property commentaire As String
    Public Property noCompagnie As Nullable(Of Integer)
    Public Property codeVille As String
    Public Property codeProv As String

    Public Overridable Property tblVille As tblVille
    Public Overridable Property tblCompagnie As tblCompagnie
    Public Overridable Property tblCompte As ICollection(Of tblCompte) = New HashSet(Of tblCompte)
    Public Overridable Property tblReservation As ICollection(Of tblReservation) = New HashSet(Of tblReservation)

End Class
