'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblChecklist
    Public Property dateSaisit As Date
    Public Property noSalle As Short
    Public Property noHotel As Byte
    Public Property codeItem As String
    Public Property statut As String
    Public Property commentaire As String
    Public Property noEmpl As Short

    Public Overridable Property tblBris As ICollection(Of tblBris) = New HashSet(Of tblBris)
    Public Overridable Property tblItem As tblItem
    Public Overridable Property tblEmploye As tblEmploye
    Public Overridable Property tblSalle As tblSalle

End Class
