'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblElementNote
    Public Property noNote As Integer
    Public Property codeTypeElement As String
    Public Property noLigne As Byte
    Public Property montantElement As Short
    Public Property dateAjoutElem As Date

    Public Overridable Property tblTypeElement As tblTypeElement
    Public Overridable Property tblNote As tblNote

End Class
