'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblFournisseur
    Public Property noFournisseur As Short
    Public Property nomFournisseur As String
    Public Property adrFournisseur As String
    Public Property CPFournisseur As String
    Public Property noTelFournisseur As String
    Public Property respFournisseur As String
    Public Property codeVille As String
    Public Property codeProv As String

    Public Overridable Property tblCatalogue As ICollection(Of tblCatalogue) = New HashSet(Of tblCatalogue)
    Public Overridable Property tblCommande As ICollection(Of tblCommande) = New HashSet(Of tblCommande)

End Class
