'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblGabarit
    Public Property codeTypeSalle As String
    Public Property codeItem As String
    Public Property quantite As Short

    Public Overridable Property tblItem As tblItem
    Public Overridable Property tblTypeSalle As tblTypeSalle

End Class
