'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHoraire
    Public Property dateHoraire As Date
    Public Property noEmpl As Short
    Public Property heureDebut As System.TimeSpan
    Public Property heureFin As System.TimeSpan

    Public Overridable Property tblEmploye As tblEmploye

End Class
