'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblInventaire
    Public Property noHotel As Byte
    Public Property codeItem As String
    Public Property Quantite As Short
    Public Property quantiteMin As Byte

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblItem As tblItem

End Class
