'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblLigneCommande
    Public Property noCommande As Integer
    Public Property codeItem As String
    Public Property quantite As Short
    Public Property prixUnitaire As Nullable(Of Decimal)

    Public Overridable Property tblCommande As tblCommande
    Public Overridable Property tblItem As tblItem

End Class
