'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblLogin
    Public Property utilisateur As String
    Public Property mdp As String
    Public Property statut As String
    Public Property noEmpl As Short

    Public Overridable Property tblEmploye As tblEmploye

End Class
