'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPeriodeTypeSalle
    Public Property codePeriode As String
    Public Property codeTypeSalle As String
    Public Property noHotel As Byte
    Public Property prixSallePeriode As Decimal

    Public Overridable Property tblPeriode As tblPeriode
    Public Overridable Property tblTypeSalleHotel As tblTypeSalleHotel

End Class
