'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPeriode
    Public Property codePeriode As String
    Public Property nomPeriode As String
    Public Property dateDebutPeriode As Date
    Public Property dateFinPeriode As Date

    Public Overridable Property tblPeriodeTypeSalle As ICollection(Of tblPeriodeTypeSalle) = New HashSet(Of tblPeriodeTypeSalle)

End Class
