'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTypeLit
    Public Property codeTypeLit As String
    Public Property descTypeLit As String

    Public Overridable Property tblSalle As ICollection(Of tblSalle) = New HashSet(Of tblSalle)

End Class
