'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBris
    Public Property noBris As Integer
    Public Property etatBris As String
    Public Property dateRepare As Nullable(Of Date)
    Public Property dateBris As Date
    Public Property noSalle As Short
    Public Property noHotel As Byte
    Public Property codeItem As String

    Public Overridable Property tblItem As tblItem
    Public Overridable Property tblSalle As tblSalle

End Class
