'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblBoiteReception
    Public Property noEmpl As Short
    Public Property noMessage As Long
    Public Property typeRecepteur As String
    Public Property etatMessage As String

    Public Overridable Property tblEmploye As tblEmploye
    Public Overridable Property tblMessage As tblMessage

End Class
