'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCommande
    Public Property noCommande As Integer
    Public Property dateCommande As Date
    Public Property prixCommande As Nullable(Of Decimal)
    Public Property etatCommande As String
    Public Property noFournisseur As Short
    Public Property noEmpl As Short

    Public Overridable Property tblEmploye As tblEmploye
    Public Overridable Property tblFournisseur As tblFournisseur
    Public Overridable Property tblLigneCommande As ICollection(Of tblLigneCommande) = New HashSet(Of tblLigneCommande)

End Class
