'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblHotel
    Public Property noHotel As Byte
    Public Property nomHotel As String
    Public Property adrHotel As String
    Public Property noTelHotel As String
    Public Property noTelecopieur As String
    Public Property noTelReserv As String
    Public Property codePostal As String
    Public Property codeVille As String

    Public Overridable Property tblChambre As ICollection(Of tblChambre) = New HashSet(Of tblChambre)
    Public Overridable Property tblEmploye As ICollection(Of tblEmploye) = New HashSet(Of tblEmploye)
    Public Overridable Property tblForfait As ICollection(Of tblForfait) = New HashSet(Of tblForfait)
    Public Overridable Property tblVille As tblVille
    Public Overridable Property tblInventaire As ICollection(Of tblInventaire) = New HashSet(Of tblInventaire)
    Public Overridable Property tblSalle As ICollection(Of tblSalle) = New HashSet(Of tblSalle)
    Public Overridable Property tblTypeChambreHotel As ICollection(Of tblTypeChambreHotel) = New HashSet(Of tblTypeChambreHotel)

End Class
