'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblItem
    Public Property codeItem As String
    Public Property nomItem As String
    Public Property descItem As String

    Public Overridable Property tblBris As ICollection(Of tblBris) = New HashSet(Of tblBris)
    Public Overridable Property tblCatalogue As ICollection(Of tblCatalogue) = New HashSet(Of tblCatalogue)
    Public Overridable Property tblChecklist As ICollection(Of tblChecklist) = New HashSet(Of tblChecklist)
    Public Overridable Property tblGabarit As ICollection(Of tblGabarit) = New HashSet(Of tblGabarit)
    Public Overridable Property tblInventaire As ICollection(Of tblInventaire) = New HashSet(Of tblInventaire)
    Public Overridable Property tblLigneCommande As ICollection(Of tblLigneCommande) = New HashSet(Of tblLigneCommande)

End Class
