'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblMessage
    Public Property noMessage As Long
    Public Property objetMessage As String
    Public Property contMessage As String
    Public Property emetteurMessage As Short

    Public Overridable Property tblBoiteReception As ICollection(Of tblBoiteReception) = New HashSet(Of tblBoiteReception)
    Public Overridable Property tblEmploye As tblEmploye
    Public Overridable Property tblPieceJointe As ICollection(Of tblPieceJointe) = New HashSet(Of tblPieceJointe)

End Class
