'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblNote
    Public Property noNote As Integer
    Public Property noReservation As Integer
    Public Property etatNote As String
    Public Property noFacture As Nullable(Of Integer)

    Public Overridable Property tblElementNote As ICollection(Of tblElementNote) = New HashSet(Of tblElementNote)
    Public Overridable Property tblFacture As tblFacture
    Public Overridable Property tblReservation As tblReservation

End Class
