'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblNote
    Public Property noNote As Integer
    Public Property noReservation As Integer
    Public Property etatNote As String

    Public Overridable Property tblElementNote As ICollection(Of tblElementNote) = New HashSet(Of tblElementNote)
    Public Overridable Property tblReservation As tblReservation
    Public Overridable Property tblFacture As ICollection(Of tblFacture) = New HashSet(Of tblFacture)

End Class
