'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblProvince
    Public Property codeProv As String
    Public Property nomProv As String
    Public Property codePays As String

    Public Overridable Property tblPays As tblPays
    Public Overridable Property tblVille As ICollection(Of tblVille) = New HashSet(Of tblVille)

End Class
