'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblReservationSalle
    Public Property noReservation As Integer
    Public Property dateDebut As Date
    Public Property dateFin As Date
    Public Property dateReserv As Date
    Public Property commentaire As String
    Public Property noSalle As Byte
    Public Property noEmpl As Short
    Public Property noClient As Integer

    Public Overridable Property tblEmploye As tblEmploye
    Public Overridable Property tblClient As tblClient
    Public Overridable Property tblSalle As tblSalle

End Class
