'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblRabais
    Public Property noRabais As Byte
    Public Property tauxRabais As Decimal
    Public Property etatRabais As String
    Public Property codeTypeSalle As String
    Public Property noHotel As Byte

    Public Overridable Property tblTypeSalleHotel As tblTypeSalleHotel
    Public Overridable Property tblReservation As ICollection(Of tblReservation) = New HashSet(Of tblReservation)

End Class
