'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTypeSalleHotel
    Public Property codeTypeSalle As String
    Public Property noHotel As Byte
    Public Property prixSalle As Nullable(Of Decimal)

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblPeriodeTypeSalle As ICollection(Of tblPeriodeTypeSalle) = New HashSet(Of tblPeriodeTypeSalle)
    Public Overridable Property tblRabais As ICollection(Of tblRabais) = New HashSet(Of tblRabais)
    Public Overridable Property tblTypeSalle As tblTypeSalle

End Class
