'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTypeChambreHotel
    Public Property codeTypeChambre As String
    Public Property noHotel As Byte
    Public Property prixChambre As Decimal

    Public Overridable Property tblHotel As tblHotel
    Public Overridable Property tblRabais As ICollection(Of tblRabais) = New HashSet(Of tblRabais)
    Public Overridable Property tblTypeChambre As tblTypeChambre

End Class
