'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblTypeSalle
    Public Property codeTypeSalle As String
    Public Property nomTypeSalle As String

    Public Overridable Property tblGabarit As ICollection(Of tblGabarit) = New HashSet(Of tblGabarit)
    Public Overridable Property tblForfait As ICollection(Of tblForfait) = New HashSet(Of tblForfait)
    Public Overridable Property tblSalle As ICollection(Of tblSalle) = New HashSet(Of tblSalle)
    Public Overridable Property tblTypeSalleHotel As ICollection(Of tblTypeSalleHotel) = New HashSet(Of tblTypeSalleHotel)

End Class
