'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré à partir d'un modèle.
'
'     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
'     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblVille
    Public Property codeVille As String
    Public Property nomVille As String
    Public Property codeProv As String

    Public Overridable Property tblHotel As ICollection(Of tblHotel) = New HashSet(Of tblHotel)
    Public Overridable Property tblProvince As tblProvince
    Public Overridable Property tblClient As ICollection(Of tblClient) = New HashSet(Of tblClient)
    Public Overridable Property tblCompagnie As ICollection(Of tblCompagnie) = New HashSet(Of tblCompagnie)
    Public Overridable Property tblEmploye As ICollection(Of tblEmploye) = New HashSet(Of tblEmploye)

End Class
